/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#1e293b",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-container": "#8590a6",
        "outline": "#75777d",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b7c8e1",
        "tertiary-fixed-dim": "#ddc39d",
        "tertiary-fixed": "#fadfb8",
        "outline-variant": "#c5c6cd",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "primary": "#091426",
        "secondary-fixed": "#d3e4fe",
        "surface-container-highest": "#e0e3e5",
        "on-primary": "#ffffff",
        "secondary": "#505f76",
        "inverse-surface": "#2d3133",
        "surface-tint": "#545f73",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#d0e1fb",
        "primary-fixed": "#d8e3fb",
        "tertiary-container": "#35260c",
        "on-surface-variant": "#45474c",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed": "#271902",
        "surface-container": "#eceef0",
        "on-secondary-fixed": "#0b1c30",
        "surface-dim": "#d8dadc",
        "tertiary": "#1e1200",
        "on-primary-fixed": "#111c2d",
        "on-secondary-container": "#54647a",
        "on-tertiary-fixed-variant": "#564427",
        "primary-fixed-dim": "#bcc7de",
        "inverse-primary": "#bcc7de",
        "on-tertiary-container": "#a38c6a",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#3c475a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        xl: "64px",
        lg: "40px",
        md: "24px",
        gutter: "24px",
        xs: "4px",
        base: "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        hanken: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
