export const COUNTRIES = [
  { name: "Afghanistan",           currency: "AFN", symbol: "؋"    },
  { name: "Albania",               currency: "ALL", symbol: "L"    },
  { name: "Algeria",               currency: "DZD", symbol: "د.ج"  },
  { name: "Angola",                currency: "AOA", symbol: "Kz"   },
  { name: "Argentina",             currency: "ARS", symbol: "$"    },
  { name: "Armenia",               currency: "AMD", symbol: "֏"    },
  { name: "Australia",             currency: "AUD", symbol: "A$"   },
  { name: "Austria",               currency: "EUR", symbol: "€"    },
  { name: "Azerbaijan",            currency: "AZN", symbol: "₼"    },
  { name: "Bahrain",               currency: "BHD", symbol: "BD"   },
  { name: "Bangladesh",            currency: "BDT", symbol: "৳"    },
  { name: "Belarus",               currency: "BYN", symbol: "Br"   },
  { name: "Belgium",               currency: "EUR", symbol: "€"    },
  { name: "Bolivia",               currency: "BOB", symbol: "Bs."  },
  { name: "Brazil",                currency: "BRL", symbol: "R$"   },
  { name: "Bulgaria",              currency: "BGN", symbol: "лв"   },
  { name: "Cambodia",              currency: "KHR", symbol: "KHR"  },
  { name: "Cameroon",              currency: "XAF", symbol: "Fr"   },
  { name: "Canada",                currency: "CAD", symbol: "CA$"  },
  { name: "Chile",                 currency: "CLP", symbol: "$"    },
  { name: "China",                 currency: "CNY", symbol: "¥"    },
  { name: "Colombia",              currency: "COP", symbol: "$"    },
  { name: "Costa Rica",            currency: "CRC", symbol: "₡"    },
  { name: "Croatia",               currency: "EUR", symbol: "€"    },
  { name: "Cuba",                  currency: "CUP", symbol: "$"    },
  { name: "Czech Republic",        currency: "CZK", symbol: "Kč"   },
  { name: "Denmark",               currency: "DKK", symbol: "kr"   },
  { name: "Dominican Republic",    currency: "DOP", symbol: "RD$"  },
  { name: "Ecuador",               currency: "USD", symbol: "$"    },
  { name: "Egypt",                 currency: "EGP", symbol: "£"    },
  { name: "El Salvador",           currency: "USD", symbol: "$"    },
  { name: "Estonia",               currency: "EUR", symbol: "€"    },
  { name: "Ethiopia",              currency: "ETB", symbol: "Br"   },
  { name: "Finland",               currency: "EUR", symbol: "€"    },
  { name: "France",                currency: "EUR", symbol: "€"    },
  { name: "Georgia",               currency: "GEL", symbol: "₾"    },
  { name: "Germany",               currency: "EUR", symbol: "€"    },
  { name: "Ghana",                 currency: "GHS", symbol: "₵"    },
  { name: "Greece",                currency: "EUR", symbol: "€"    },
  { name: "Guatemala",             currency: "GTQ", symbol: "Q"    },
  { name: "Honduras",              currency: "HNL", symbol: "L"    },
  { name: "Hong Kong",             currency: "HKD", symbol: "HK$"  },
  { name: "Hungary",               currency: "HUF", symbol: "Ft"   },
  { name: "Iceland",               currency: "ISK", symbol: "kr"   },
  { name: "India",                 currency: "INR", symbol: "₹"    },
  { name: "Indonesia",             currency: "IDR", symbol: "Rp"   },
  { name: "Iran",                  currency: "IRR", symbol: "IRR"  },
  { name: "Iraq",                  currency: "IQD", symbol: "IQD"  },
  { name: "Ireland",               currency: "EUR", symbol: "€"    },
  { name: "Israel",                currency: "ILS", symbol: "₪"    },
  { name: "Italy",                 currency: "EUR", symbol: "€"    },
  { name: "Jamaica",               currency: "JMD", symbol: "J$"   },
  { name: "Japan",                 currency: "JPY", symbol: "¥"    },
  { name: "Jordan",                currency: "JOD", symbol: "JOD"  },
  { name: "Kazakhstan",            currency: "KZT", symbol: "₸"    },
  { name: "Kenya",                 currency: "KES", symbol: "KSh"  },
  { name: "Kuwait",                currency: "KWD", symbol: "KD"   },
  { name: "Latvia",                currency: "EUR", symbol: "€"    },
  { name: "Lebanon",               currency: "LBP", symbol: "LBP"  },
  { name: "Lithuania",             currency: "EUR", symbol: "€"    },
  { name: "Luxembourg",            currency: "EUR", symbol: "€"    },
  { name: "Malaysia",              currency: "MYR", symbol: "RM"   },
  { name: "Malta",                 currency: "EUR", symbol: "€"    },
  { name: "Mexico",                currency: "MXN", symbol: "$"    },
  { name: "Moldova",               currency: "MDL", symbol: "L"    },
  { name: "Morocco",               currency: "MAD", symbol: "MAD"  },
  { name: "Mozambique",            currency: "MZN", symbol: "MT"   },
  { name: "Myanmar",               currency: "MMK", symbol: "K"    },
  { name: "Namibia",               currency: "NAD", symbol: "N$"   },
  { name: "Nepal",                 currency: "NPR", symbol: "₨"    },
  { name: "Netherlands",           currency: "EUR", symbol: "€"    },
  { name: "New Zealand",           currency: "NZD", symbol: "NZ$"  },
  { name: "Nicaragua",             currency: "NIO", symbol: "C$"   },
  { name: "Nigeria",               currency: "NGN", symbol: "₦"    },
  { name: "Norway",                currency: "NOK", symbol: "kr"   },
  { name: "Oman",                  currency: "OMR", symbol: "OMR"  },
  { name: "Pakistan",              currency: "PKR", symbol: "₨"    },
  { name: "Panama",                currency: "PAB", symbol: "B/."  },
  { name: "Paraguay",              currency: "PYG", symbol: "₲"    },
  { name: "Peru",                  currency: "PEN", symbol: "S/."  },
  { name: "Philippines",           currency: "PHP", symbol: "₱"    },
  { name: "Poland",                currency: "PLN", symbol: "zł"   },
  { name: "Portugal",              currency: "EUR", symbol: "€"    },
  { name: "Qatar",                 currency: "QAR", symbol: "QR"   },
  { name: "Romania",               currency: "RON", symbol: "lei"  },
  { name: "Russia",                currency: "RUB", symbol: "₽"    },
  { name: "Rwanda",                currency: "RWF", symbol: "Fr"   },
  { name: "Saudi Arabia",          currency: "SAR", symbol: "SR"   },
  { name: "Senegal",               currency: "XOF", symbol: "Fr"   },
  { name: "Serbia",                currency: "RSD", symbol: "din"  },
  { name: "Singapore",             currency: "SGD", symbol: "S$"   },
  { name: "Slovakia",              currency: "EUR", symbol: "€"    },
  { name: "Slovenia",              currency: "EUR", symbol: "€"    },
  { name: "Somalia",               currency: "SOS", symbol: "Sh"   },
  { name: "South Africa",          currency: "ZAR", symbol: "R"    },
  { name: "South Korea",           currency: "KRW", symbol: "₩"    },
  { name: "Spain",                 currency: "EUR", symbol: "€"    },
  { name: "Sri Lanka",             currency: "LKR", symbol: "₨"    },
  { name: "Sweden",                currency: "SEK", symbol: "kr"   },
  { name: "Switzerland",           currency: "CHF", symbol: "Fr"   },
  { name: "Taiwan",                currency: "TWD", symbol: "NT$"  },
  { name: "Tanzania",              currency: "TZS", symbol: "Sh"   },
  { name: "Thailand",              currency: "THB", symbol: "฿"    },
  { name: "Tunisia",               currency: "TND", symbol: "TND"  },
  { name: "Turkey",                currency: "TRY", symbol: "₺"    },
  { name: "Uganda",                currency: "UGX", symbol: "Sh"   },
  { name: "Ukraine",               currency: "UAH", symbol: "₴"    },
  { name: "United Arab Emirates",  currency: "AED", symbol: "AED"  },
  { name: "United Kingdom",        currency: "GBP", symbol: "£"    },
  { name: "United States",         currency: "USD", symbol: "$"    },
  { name: "Uruguay",               currency: "UYU", symbol: "$U"   },
  { name: "Uzbekistan",            currency: "UZS", symbol: "soum" },
  { name: "Venezuela",             currency: "VES", symbol: "Bs.S" },
  { name: "Vietnam",               currency: "VND", symbol: "₫"    },
  { name: "Yemen",                 currency: "YER", symbol: "YER"  },
  { name: "Zambia",                currency: "ZMW", symbol: "ZK"   },
  { name: "Zimbabwe",              currency: "ZWL", symbol: "$"    },
];

export const CURRENCIES = [
  { code: "USD", symbol: "$",    name: "US Dollar" },
  { code: "EUR", symbol: "€",    name: "Euro" },
  { code: "GBP", symbol: "£",    name: "British Pound" },
  { code: "CAD", symbol: "CA$",  name: "Canadian Dollar" },
  { code: "AUD", symbol: "A$",   name: "Australian Dollar" },
  { code: "JPY", symbol: "¥",    name: "Japanese Yen" },
  { code: "CHF", symbol: "Fr",   name: "Swiss Franc" },
  { code: "CNY", symbol: "¥",    name: "Chinese Yuan" },
  { code: "INR", symbol: "₹",    name: "Indian Rupee" },
  { code: "NGN", symbol: "₦",    name: "Nigerian Naira" },
  { code: "ZAR", symbol: "R",    name: "South African Rand" },
  { code: "GHS", symbol: "₵",    name: "Ghanaian Cedi" },
  { code: "KES", symbol: "KSh",  name: "Kenyan Shilling" },
  { code: "BRL", symbol: "R$",   name: "Brazilian Real" },
  { code: "MXN", symbol: "$",    name: "Mexican Peso" },
  { code: "SGD", symbol: "S$",   name: "Singapore Dollar" },
  { code: "AED", symbol: "AED",  name: "UAE Dirham" },
  { code: "SAR", symbol: "SR",   name: "Saudi Riyal" },
  { code: "NZD", symbol: "NZ$",  name: "New Zealand Dollar" },
  { code: "HKD", symbol: "HK$",  name: "Hong Kong Dollar" },
  { code: "NOK", symbol: "kr",   name: "Norwegian Krone" },
  { code: "SEK", symbol: "kr",   name: "Swedish Krona" },
  { code: "DKK", symbol: "kr",   name: "Danish Krone" },
  { code: "PLN", symbol: "zł",   name: "Polish Zloty" },
  { code: "TRY", symbol: "₺",    name: "Turkish Lira" },
  { code: "RUB", symbol: "₽",    name: "Russian Ruble" },
  { code: "KRW", symbol: "₩",    name: "South Korean Won" },
  { code: "PHP", symbol: "₱",    name: "Philippine Peso" },
  { code: "THB", symbol: "฿",    name: "Thai Baht" },
  { code: "MYR", symbol: "RM",   name: "Malaysian Ringgit" },
  { code: "IDR", symbol: "Rp",   name: "Indonesian Rupiah" },
  { code: "EGP", symbol: "£",    name: "Egyptian Pound" },
  { code: "PKR", symbol: "₨",    name: "Pakistani Rupee" },
  { code: "BDT", symbol: "৳",    name: "Bangladeshi Taka" },
  { code: "VND", symbol: "₫",    name: "Vietnamese Dong" },
  { code: "UAH", symbol: "₴",    name: "Ukrainian Hryvnia" },
  { code: "CZK", symbol: "Kč",   name: "Czech Koruna" },
  { code: "HUF", symbol: "Ft",   name: "Hungarian Forint" },
  { code: "ILS", symbol: "₪",    name: "Israeli Shekel" },
  { code: "QAR", symbol: "QR",   name: "Qatari Riyal" },
  { code: "TWD", symbol: "NT$",  name: "Taiwan Dollar" },
  { code: "MAD", symbol: "MAD",  name: "Moroccan Dirham" },
];