export const LANGUAGES = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "pl", name: "Polish", nativeName: "Polski", flag: "🇵🇱" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", flag: "🇸🇪" },
  { code: "no", name: "Norwegian", nativeName: "Norsk", flag: "🇳🇴" },
  { code: "da", name: "Danish", nativeName: "Dansk", flag: "🇩🇰" },
  { code: "fi", name: "Finnish", nativeName: "Suomi", flag: "🇫🇮" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "th", name: "Thai", nativeName: "ภาษาไทย", flag: "🇹🇭" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", flag: "🇺🇦" },
  { code: "cs", name: "Czech", nativeName: "Čeština", flag: "🇨🇿" },
  { code: "ro", name: "Romanian", nativeName: "Română", flag: "🇷🇴" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar", flag: "🇭🇺" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", flag: "🇬🇷" },
  { code: "he", name: "Hebrew", nativeName: "עברית", flag: "🇮🇱" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili", flag: "🇰🇪" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá", flag: "🇳🇬" },
  { code: "ig", name: "Igbo", nativeName: "Igbo", flag: "🇳🇬" },
  { code: "ha", name: "Hausa", nativeName: "Hausa", flag: "🇳🇬" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ", flag: "🇪🇹" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇧🇩" },
  { code: "ur", name: "Urdu", nativeName: "اردو", flag: "🇵🇰" },
  { code: "fa", name: "Persian", nativeName: "فارسی", flag: "🇮🇷" },
  { code: "tl", name: "Filipino", nativeName: "Filipino", flag: "🇵🇭" },
];

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard Overview",
    balance: "Available Balance",
    send: "Send Money",
    deposit: "Deposit",
    request: "Request",
    payBills: "Pay Bills",
    transactions: "Transactions",
    analytics: "Analytics",
    card: "Virtual Card",
    profile: "Profile",
    crypto: "Crypto",
    quickActions: "Quick Actions",
    totalSpent: "Total Spent (Month)",
    totalReceived: "Total Received",
    recentTransactions: "Recent Transactions",
    seeAll: "See All",
    signOut: "Sign Out",
    settings: "Settings",
    language: "Language",
    selectLanguage: "Select Language",
  },
  fr: {
    dashboard: "Aperçu du Tableau de Bord",
    balance: "Solde Disponible",
    send: "Envoyer de l'Argent",
    deposit: "Dépôt",
    request: "Demande",
    payBills: "Payer les Factures",
    transactions: "Transactions",
    analytics: "Analytique",
    card: "Carte Virtuelle",
    profile: "Profil",
    crypto: "Crypto",
    quickActions: "Actions Rapides",
    totalSpent: "Total Dépensé (Mois)",
    totalReceived: "Total Reçu",
    recentTransactions: "Transactions Récentes",
    seeAll: "Tout Voir",
    signOut: "Se Déconnecter",
    settings: "Paramètres",
    language: "Langue",
    selectLanguage: "Sélectionner la Langue",
  },
  es: {
    dashboard: "Resumen del Panel",
    balance: "Saldo Disponible",
    send: "Enviar Dinero",
    deposit: "Depósito",
    request: "Solicitud",
    payBills: "Pagar Facturas",
    transactions: "Transacciones",
    analytics: "Analítica",
    card: "Tarjeta Virtual",
    profile: "Perfil",
    crypto: "Cripto",
    quickActions: "Acciones Rápidas",
    totalSpent: "Total Gastado (Mes)",
    totalReceived: "Total Recibido",
    recentTransactions: "Transacciones Recientes",
    seeAll: "Ver Todo",
    signOut: "Cerrar Sesión",
    settings: "Configuración",
    language: "Idioma",
    selectLanguage: "Seleccionar Idioma",
  },
  ar: {
    dashboard: "نظرة عامة على لوحة التحكم",
    balance: "الرصيد المتاح",
    send: "إرسال الأموال",
    deposit: "إيداع",
    request: "طلب",
    payBills: "دفع الفواتير",
    transactions: "المعاملات",
    analytics: "التحليلات",
    card: "البطاقة الافتراضية",
    profile: "الملف الشخصي",
    crypto: "العملات المشفرة",
    quickActions: "الإجراءات السريعة",
    totalSpent: "إجمالي الإنفاق (الشهر)",
    totalReceived: "إجمالي المستلم",
    recentTransactions: "المعاملات الأخيرة",
    seeAll: "عرض الكل",
    signOut: "تسجيل الخروج",
    settings: "الإعدادات",
    language: "اللغة",
    selectLanguage: "اختر اللغة",
  },
  pt: {
    dashboard: "Visão Geral do Painel",
    balance: "Saldo Disponível",
    send: "Enviar Dinheiro",
    deposit: "Depósito",
    request: "Pedido",
    payBills: "Pagar Contas",
    transactions: "Transações",
    analytics: "Análise",
    card: "Cartão Virtual",
    profile: "Perfil",
    crypto: "Cripto",
    quickActions: "Ações Rápidas",
    totalSpent: "Total Gasto (Mês)",
    totalReceived: "Total Recebido",
    recentTransactions: "Transações Recentes",
    seeAll: "Ver Tudo",
    signOut: "Sair",
    settings: "Configurações",
    language: "Idioma",
    selectLanguage: "Selecionar Idioma",
  },
  de: {
    dashboard: "Dashboard-Übersicht",
    balance: "Verfügbares Guthaben",
    send: "Geld Senden",
    deposit: "Einzahlung",
    request: "Anfrage",
    payBills: "Rechnungen Bezahlen",
    transactions: "Transaktionen",
    analytics: "Analytik",
    card: "Virtuelle Karte",
    profile: "Profil",
    crypto: "Krypto",
    quickActions: "Schnellaktionen",
    totalSpent: "Gesamt Ausgegeben (Monat)",
    totalReceived: "Gesamt Erhalten",
    recentTransactions: "Letzte Transaktionen",
    seeAll: "Alle Anzeigen",
    signOut: "Abmelden",
    settings: "Einstellungen",
    language: "Sprache",
    selectLanguage: "Sprache Auswählen",
  },
  zh: {
    dashboard: "仪表板概览",
    balance: "可用余额",
    send: "汇款",
    deposit: "存款",
    request: "请求",
    payBills: "支付账单",
    transactions: "交易",
    analytics: "分析",
    card: "虚拟卡",
    profile: "个人资料",
    crypto: "加密货币",
    quickActions: "快捷操作",
    totalSpent: "本月总支出",
    totalReceived: "总收入",
    recentTransactions: "最近交易",
    seeAll: "查看全部",
    signOut: "退出登录",
    settings: "设置",
    language: "语言",
    selectLanguage: "选择语言",
  },
  yo: {
    dashboard: "Akọsilẹ Dashboard",
    balance: "Owo Ti O Wa",
    send: "Fi Owo Ranṣẹ",
    deposit: "Fi Owo Sii",
    request: "Beere",
    payBills: "San Isan-owo",
    transactions: "Awọn Iṣowo",
    analytics: "Itupalẹ",
    card: "Kaadi Foju",
    profile: "Profaili",
    crypto: "Kirip'to",
    quickActions: "Awọn Igbese Kiakia",
    totalSpent: "Apapọ Ti Lo (Oṣu)",
    totalReceived: "Apapọ Ti Gba",
    recentTransactions: "Awọn Iṣowo Laipẹ",
    seeAll: "Wo Gbogbo",
    signOut: "Jade",
    settings: "Eto",
    language: "Ede",
    selectLanguage: "Yan Ede",
  },
};

export function t(lang, key) {
  const translations = TRANSLATIONS[lang] || TRANSLATIONS.en;
  return translations[key] || TRANSLATIONS.en[key] || key;
}